[package]
name = "quantum"
version = "6.0.3"
edition = "2024"

[dependencies]
poise = "0.6.1"
prost = "0.14.1"
reqwest = "0.12.24"
serde_json = "1.0.145"
tokio = { version = "1.47.0", features = ["macros", "rt-multi-thread"] }
tonic = { version = "0.14.2", features = ["tls-native-roots", "tls-ring"] }
tonic-prost = "0.14.2"

[build-dependencies]
tonic-prost-build = "0.14.2"

