[package]
name = "quantum"
version = "5.3.0"
edition = "2021"

[dependencies]
const_format = "0.2.34"
dotenv = "0.15.0"
libsql = "0.6.0"
poise = { version = "0.6.1", features = ["cache"] }
serde_json = "1.0.137"
tokio = { version = "1.43.0", features = ["rt-multi-thread"] }

