name: Documentation


on:
  push:
    branches:
      - '*-dev'
    paths:
      - 'docs/**'
      - '.github/workflows/documentation.yml'


jobs:

  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Install mdbook-admonish
        run: cargo install mdbook mdbook-admonish

      - name: Build Book
        run: |
          cd docs && mdbook build

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'docs/book'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
